[FIX] add missing header sys/time.h
sys/time.h is missing when a musl based toolchain is used.

Fixes:
/stack/src/arch/linux/target-linux.c:118:21: error: storage size of ‘timeout’ isn’t known
     struct  timeval timeout;

Signed-off-by: Romain Naour <romain.naour@openwide.fr>